unit Common;

interface

const
  MSG_TEST_APP_BASE    = 79000;
  MSG_BUTTON_BASE      = MSG_TEST_APP_BASE + 100;
  MSG_CHECKBOX_BASE    = MSG_TEST_APP_BASE + 200;
  MSG_RADIOBUTTON_BASE = MSG_TEST_APP_BASE + 300;
  MSG_STRINGVIEW_BASE  = MSG_TEST_APP_BASE + 400;
  MSG_MENU_BASE        = MSG_TEST_APP_BASE + 500;
  MSG_STATUSBAR_BASE   = MSG_TEST_APP_BASE + 600;

implementation

end.